### PR TITLE
Upgraded reports, HTML side

### PR DESCRIPTION
**Pull request by meyerweb**

### CODE REVIEW

**Comment by meyerweb** [comment]
Filter form removed as per discussion on issue #8.  I believe this is ready to merge (but I cannot do so myself).

**Comment by bkardell** [comment]
Thanks!

**Comment by meyerweb** [comment]
Oops, apparently I left some needed markup out of the script to make the subgrid alignment work.  Will submit a separate PR.

**Comment by bkardell** [comment]
You can update https://github.com/bkardell/bcd-watch/blob/main/store/bookkeeping.json to make both dates match the older date in order to force it to re-run if you like

**Pull request merged**
